import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  buildMsplineBasis,
  evalBasis,
  msplineConstantHazard,
  rw1PriorWeights
} from "../mlumr/mspline";
import { survivalDistInfo, survivalModelName } from "../mlumr/survivalDist";
import { parseCsv } from "../mlumr/csv";
import { buildMlumrData } from "../mlumr/data";
import { addIntegration } from "../mlumr/integration";
import { buildStanData, stanDataJson } from "../mlumr/stanData";
import { exampleForFamily } from "../examples/examples";
import type { CovariateSpec } from "../mlumr/types";

// M-spline / I-spline basis validated against R splines2 (see /tmp/mspline_ref.txt,
// generated by /tmp/mspline_ref.R: internal=[2,5,9], boundary=[0,12]).
const REF = "/tmp/mspline_ref.txt";

function parseRef(): Record<number, { n: number; M: number[][]; I: number[][] }> {
  const out: Record<number, { n: number; M: number[][]; I: number[][] }> = {};
  let deg = -1;
  let mode: "M" | "I" | null = null;
  for (const line of readFileSync(REF, "utf8").split(/\r?\n/)) {
    const dm = line.match(/^DEGREE (\d+)\s+n_scoef=(\d+)/);
    if (dm) { deg = Number(dm[1]); out[deg] = { n: Number(dm[2]), M: [], I: [] }; mode = null; continue; }
    if (/^M:/.test(line)) { mode = "M"; continue; }
    if (/^I:/.test(line)) { mode = "I"; continue; }
    const rm = line.match(/t=[-0-9.]+\s+(.+)$/);
    if (rm && mode && deg >= 0) {
      const nums = rm[1].trim().split(/\s+/).map(Number).filter(Number.isFinite);
      if (nums.length) out[deg][mode].push(nums);
    }
  }
  return out;
}

const TIMES = [0, 0.5, 2, 5, 7.3, 12, 14];
const INTERNAL = [2, 5, 9];
const BOUNDARY: [number, number] = [0, 12];
const KNOTS = { internal: INTERNAL, boundary: BOUNDARY, nKnots: INTERNAL.length };

describe("M-spline basis matches R splines2", () => {
  const ref = parseRef();
  for (const degree of [0, 1, 2, 3]) {
    it(`degree ${degree} M and I bases match to 1e-9`, () => {
      const spec = buildMsplineBasis(KNOTS, degree);
      const M = evalBasis(spec, TIMES, false);
      const I = evalBasis(spec, TIMES, true);
      expect(M[0].length).toBe(ref[degree].n);
      let maxAbs = 0;
      for (let i = 0; i < TIMES.length; i++) {
        for (let j = 0; j < ref[degree].n; j++) {
          maxAbs = Math.max(maxAbs, Math.abs(M[i][j] - ref[degree].M[i][j]));
          maxAbs = Math.max(maxAbs, Math.abs(I[i][j] - ref[degree].I[i][j]));
        }
      }
      expect(maxAbs).toBeLessThan(1e-9);
    });
  }
});

describe("constant-hazard anchor and RW1 weights match R", () => {
  // From /tmp/chrw_ref.txt (mlumr:::.mspline_constant_hazard / .rw1_prior_weights).
  const refLines = readFileSync("/tmp/chrw_ref.txt", "utf8").split(/\r?\n/).filter((l: string) => l.startsWith("DEG"));
  for (const ln of refLines) {
    const m = ln.match(/^DEG (\d+) nscoef (\d+) CH ([-0-9.,e]+) RW ([-0-9.,e]+)/);
    if (!m) continue;
    const degree = Number(m[1]);
    const Rch = m[3].split(",").map(Number);
    const Rrw = m[4].split(",").map(Number);
    it(`degree ${degree} const-hazard + RW1 match to 1e-9`, () => {
      const spec = buildMsplineBasis(KNOTS, degree);
      const ch = msplineConstantHazard(spec);
      const rw = rw1PriorWeights(spec);
      expect(ch.length).toBe(Rch.length);
      expect(rw.length).toBe(Rrw.length);
      let maxAbs = 0;
      for (let i = 0; i < Rch.length; i++) maxAbs = Math.max(maxAbs, Math.abs(ch[i] - Rch[i]));
      for (let i = 0; i < Rrw.length; i++) maxAbs = Math.max(maxAbs, Math.abs(rw[i] - Rrw[i]));
      expect(maxAbs).toBeLessThan(1e-9);
    });
  }
});

describe("survival distribution metadata mirrors R", () => {
  const cases: Array<[string, number | null, boolean, number, string]> = [
    ["exponential", 1, true, 0, "mlumr_survival"],
    ["weibull", 2, true, 1, "mlumr_survival"],
    ["gompertz", 3, true, 1, "mlumr_survival"],
    ["exponential-aft", 4, false, 0, "mlumr_survival"],
    ["weibull-aft", 5, false, 1, "mlumr_survival"],
    ["lognormal", 6, false, 1, "mlumr_survival"],
    ["loglogistic", 7, false, 1, "mlumr_survival"],
    ["gamma", 8, false, 1, "mlumr_survival"],
    ["gengamma", 9, false, 2, "mlumr_survival"],
    ["mspline", null, true, 0, "mlumr_survival_mspline"],
    ["pexp", null, true, 0, "mlumr_survival_mspline"]
  ];
  for (const [dist, code, isPh, nAux, prefix] of cases) {
    it(`${dist}`, () => {
      const info = survivalDistInfo(dist);
      expect(info.distCode).toBe(code);
      expect(info.isPh).toBe(isPh);
      expect(info.nAux).toBe(nAux);
      expect(info.stanPrefix).toBe(prefix);
    });
  }
  it("survivalModelName picks mspline prefix for flexible", () => {
    expect(survivalModelName("weibull", "spfa")).toBe("mlumr_survival_spfa");
    expect(survivalModelName("gengamma", "relaxed")).toBe("mlumr_survival_relaxed");
    expect(survivalModelName("mspline", "spfa")).toBe("mlumr_survival_mspline_spfa");
    expect(survivalModelName("pexp", "relaxed")).toBe("mlumr_survival_mspline_relaxed");
  });
});

describe("survival Stan data assembly", () => {
  const ex = exampleForFamily("survival");
  const ipd = parseCsv(ex.ipdCsv);
  const agd = parseCsv(ex.agdCsv);
  const specs = ex.covariateSpecs as Record<string, CovariateSpec>;

  function stanFor(distribution: string) {
    const base = buildMlumrData("survival", ipd, agd, ex.mapping);
    const data = addIntegration(base, specs, { nInt: 16 });
    const sd = buildStanData(data, { link: "log", survival: { distribution, nKnots: 5 } });
    return JSON.parse(stanDataJson(sd)) as Record<string, unknown>;
  }

  it("example data parses", () => {
    expect(ipd.length).toBeGreaterThan(5);
    expect(agd.length).toBeGreaterThan(2);
  });

  it("parametric (weibull) emits required fields", () => {
    const j = stanFor("weibull");
    for (const k of ["n_ipd", "n_agd", "ipd_time", "ipd_status", "agd_time", "agd_status",
      "agd_arm", "n_int", "X_int", "dist", "n_pred_times", "pred_times",
      "n_rmst_grid", "rmst_grid_times", "prior_aux_location"]) {
      expect(j, `missing ${k}`).toHaveProperty(k);
    }
    expect(j.dist).toBe(2);
  });

  it("flexible (mspline) emits basis fields and no raw dist", () => {
    const j = stanFor("mspline");
    for (const k of ["n_scoef", "b_ipd", "ib_ipd", "ib_ipd_start", "ib_ipd_delay",
      "b_agd", "ib_agd", "pred_basis", "pred_ibasis", "rmst_ibasis",
      "lscoef_prior_mean", "lscoef_weights", "prior_sigma_smooth_location"]) {
      expect(j, `missing ${k}`).toHaveProperty(k);
    }
    expect((j.n_scoef as number)).toBeGreaterThanOrEqual(2);
  });
});
