import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  buildMsplineBasis,
  evalBasis,
  msplineConstantHazard,
  rw1PriorWeights
} from "../mlumr/mspline";
import { survivalDistInfo, survivalModelName } from "../mlumr/survivalDist";
import { parseCsv } from "../mlumr/csv";
import { buildMlumrData } from "../mlumr/data";
import { addIntegration } from "../mlumr/integration";
import { buildStanData, stanDataJson } from "../mlumr/stanData";
import { exampleForFamily } from "../examples/examples";
import type { CovariateSpec, ModelType } from "../mlumr/types";

// M-spline / I-spline basis validated against R splines2. The reference values
// live in fixtures/mspline-reference.txt and are regenerated by the R script
// beside them (internal=[2,5,9], boundary=[0,12]). Resolved relative to this
// file so the suite runs on any checkout; it previously read an absolute path
// under /tmp holding a scratch file that was never committed, so the whole
// suite failed to load anywhere but the machine that generated it.
const REF = fileURLToPath(new URL("./fixtures/mspline-reference.txt", import.meta.url));

function parseRef(): Record<number, { n: number; M: number[][]; I: number[][] }> {
  const out: Record<number, { n: number; M: number[][]; I: number[][] }> = {};
  let deg = -1;
  let mode: "M" | "I" | null = null;
  for (const line of readFileSync(REF, "utf8").split(/\r?\n/)) {
    const dm = line.match(/^DEGREE (\d+)\s+n_scoef=(\d+)/);
    if (dm) { deg = Number(dm[1]); out[deg] = { n: Number(dm[2]), M: [], I: [] }; mode = null; continue; }
    if (/^M:/.test(line)) { mode = "M"; continue; }
    if (/^I:/.test(line)) { mode = "I"; continue; }
    const rm = line.match(/t=[-0-9.]+\s+(.+)$/);
    if (rm && mode && deg >= 0) {
      const nums = rm[1].trim().split(/\s+/).map(Number).filter(Number.isFinite);
      if (nums.length) out[deg][mode].push(nums);
    }
  }
  return out;
}

const TIMES = [0, 0.5, 2, 5, 7.3, 12, 14];
const INTERNAL = [2, 5, 9];
const BOUNDARY: [number, number] = [0, 12];
const KNOTS = { internal: INTERNAL, boundary: BOUNDARY, nKnots: INTERNAL.length };

describe("M-spline basis matches R splines2", () => {
  const ref = parseRef();
  for (const degree of [0, 1, 2, 3]) {
    it(`degree ${degree} M and I bases match to 1e-9`, () => {
      const spec = buildMsplineBasis(KNOTS, degree);
      const M = evalBasis(spec, TIMES, false);
      const I = evalBasis(spec, TIMES, true);
      expect(M[0].length).toBe(ref[degree].n);
      let maxAbs = 0;
      for (let i = 0; i < TIMES.length; i++) {
        for (let j = 0; j < ref[degree].n; j++) {
          maxAbs = Math.max(maxAbs, Math.abs(M[i][j] - ref[degree].M[i][j]));
          maxAbs = Math.max(maxAbs, Math.abs(I[i][j] - ref[degree].I[i][j]));
        }
      }
      expect(maxAbs).toBeLessThan(1e-9);
    });
  }
});

describe("constant-hazard anchor and RW1 weights match R", () => {
  // From fixtures/anchor-weights-reference.txt, regenerated by the R script
  // beside it out of mlumr:::.mspline_constant_hazard / .rw1_prior_weights.
  const CHRW = fileURLToPath(new URL("./fixtures/anchor-weights-reference.txt", import.meta.url));
  const refLines = readFileSync(CHRW, "utf8").split(/\r?\n/).filter((l: string) => l.startsWith("DEG"));
  for (const ln of refLines) {
    const m = ln.match(/^DEG (\d+) nscoef (\d+) CH ([-0-9.,e]+) RW ([-0-9.,e]+)/);
    if (!m) continue;
    const degree = Number(m[1]);
    const Rch = m[3].split(",").map(Number);
    const Rrw = m[4].split(",").map(Number);
    it(`degree ${degree} const-hazard + RW1 match to 1e-9`, () => {
      const spec = buildMsplineBasis(KNOTS, degree);
      const ch = msplineConstantHazard(spec);
      const rw = rw1PriorWeights(spec);
      expect(ch.length).toBe(Rch.length);
      expect(rw.length).toBe(Rrw.length);
      let maxAbs = 0;
      for (let i = 0; i < Rch.length; i++) maxAbs = Math.max(maxAbs, Math.abs(ch[i] - Rch[i]));
      for (let i = 0; i < Rrw.length; i++) maxAbs = Math.max(maxAbs, Math.abs(rw[i] - Rrw[i]));
      expect(maxAbs).toBeLessThan(1e-9);
    });
  }
});

describe("survival distribution metadata mirrors R", () => {
  const cases: Array<[string, number | null, boolean, number, string]> = [
    ["exponential", 1, true, 0, "mlumr_survival"],
    ["weibull", 2, true, 1, "mlumr_survival"],
    ["gompertz", 3, true, 1, "mlumr_survival"],
    ["exponential-aft", 4, false, 0, "mlumr_survival"],
    ["weibull-aft", 5, false, 1, "mlumr_survival"],
    ["lognormal", 6, false, 1, "mlumr_survival"],
    ["loglogistic", 7, false, 1, "mlumr_survival"],
    ["gamma", 8, false, 1, "mlumr_survival"],
    ["gengamma", 9, false, 2, "mlumr_survival"],
    ["mspline", null, true, 0, "mlumr_survival_mspline"],
    ["pexp", null, true, 0, "mlumr_survival_mspline"]
  ];
  for (const [dist, code, isPh, nAux, prefix] of cases) {
    it(`${dist}`, () => {
      const info = survivalDistInfo(dist);
      expect(info.distCode).toBe(code);
      expect(info.isPh).toBe(isPh);
      expect(info.nAux).toBe(nAux);
      expect(info.stanPrefix).toBe(prefix);
    });
  }
  it("survivalModelName picks mspline prefix for flexible", () => {
    expect(survivalModelName("weibull", "spfa")).toBe("mlumr_survival_spfa");
    expect(survivalModelName("gengamma", "relaxed")).toBe("mlumr_survival_relaxed");
    expect(survivalModelName("mspline", "spfa")).toBe("mlumr_survival_mspline_spfa");
    expect(survivalModelName("pexp", "relaxed")).toBe("mlumr_survival_mspline_relaxed");
  });
});

describe("survival Stan data assembly", () => {
  const ex = exampleForFamily("survival");
  const ipd = parseCsv(ex.ipdCsv);
  const agd = parseCsv(ex.agdCsv);
  const specs = ex.covariateSpecs as Record<string, CovariateSpec>;

  function stanFor(distribution: string, model: ModelType = "spfa") {
    const base = buildMlumrData("survival", ipd, agd, ex.mapping);
    const data = addIntegration(base, specs, { nInt: 16 });
    const sd = buildStanData(data, { link: "log", survival: { distribution, nKnots: 5 }, model });
    return JSON.parse(stanDataJson(sd)) as Record<string, unknown>;
  }

  it("example data parses", () => {
    expect(ipd.length).toBeGreaterThan(5);
    expect(agd.length).toBeGreaterThan(2);
  });

  it("parametric (weibull) emits required fields", () => {
    const j = stanFor("weibull");
    for (const k of ["n_ipd", "n_agd", "ipd_time", "ipd_status", "agd_time", "agd_status",
      "agd_arm", "n_int", "X_int", "dist", "n_pred_times", "pred_times",
      "n_rmst_grid", "rmst_grid_times", "prior_aux_location"]) {
      expect(j, `missing ${k}`).toHaveProperty(k);
    }
    expect(j.dist).toBe(2);
  });

  it("flexible (mspline) emits basis fields and no raw dist", () => {
    const j = stanFor("mspline");
    for (const k of ["n_scoef", "b_ipd", "ib_ipd", "ib_ipd_start", "ib_ipd_delay",
      "b_agd", "ib_agd", "pred_basis", "pred_ibasis", "rmst_ibasis",
      "lscoef_prior_mean", "lscoef_weights", "prior_sigma_smooth_location"]) {
      expect(j, `missing ${k}`).toHaveProperty(k);
    }
    expect((j.n_scoef as number)).toBeGreaterThanOrEqual(2);
  });

  it.each(["spfa", "relaxed"] as const)("emits the combined QR design (%s) with a single arm", (variant) => {
    const j = stanFor("weibull", variant);
    const nCov = j.n_cov as number;
    const nIpd = j.n_ipd as number;
    const expectedNb = variant === "relaxed" ? 2 + 2 * nCov : 2 + nCov;

    expect(j.qr).toBe(0);
    expect(j.nB).toBe(expectedNb);
    expect(j.n_agd_rows).toBe(1); // survival always collapses to one comparator arm

    const xqIpd = j.Xq_ipd as number[][];
    expect(xqIpd).toHaveLength(nIpd);
    expect(xqIpd[0]).toHaveLength(expectedNb);
    expect(xqIpd[0].slice(0, 2)).toEqual([1, 0]);

    const xqInt = j.Xq_int as number[][][];
    expect(xqInt).toHaveLength(1); // one arm
    expect(xqInt[0][0]).toHaveLength(expectedNb);
    expect(xqInt[0][0].slice(0, 2)).toEqual([0, 1]);

    expect(j.R_inv as number[][]).toHaveLength(expectedNb);
  });

  it("mspline survival also emits the combined design", () => {
    const j = stanFor("mspline", "relaxed");
    expect(j.qr).toBe(0);
    expect(j.nB).toBe(2 + 2 * (j.n_cov as number));
    expect(j.Xq_ipd).toBeDefined();
    expect(j.Xq_int).toBeDefined();
    expect(j.R_inv).toBeDefined();
  });
});

// These variables were declared by the Stan models but never emitted by the app,
// so the normal and survival models could not read their data at all. The two
// matrix-valued ones were emitted, but flat, where Stan declares
// `matrix[n_scoef - 1, n_strata]`. Both failures are invisible until a model is
// actually run in a browser, which is why they are pinned here.
describe("Stan data contract for variables the app used to omit", () => {
  const ex = exampleForFamily("survival");
  const ipd = parseCsv(ex.ipdCsv);
  const agd = parseCsv(ex.agdCsv);
  const specs = ex.covariateSpecs as Record<string, CovariateSpec>;

  function survivalStan(distribution: string) {
    const base = buildMlumrData("survival", ipd, agd, ex.mapping);
    const data = addIntegration(base, specs, { nInt: 16 });
    return JSON.parse(
      stanDataJson(buildStanData(data, {
        link: "log", survival: { distribution, nKnots: 5 }, model: "spfa"
      }))
    ) as Record<string, unknown>;
  }

  it("every survival variant declares a baseline stratum count", () => {
    for (const d of ["weibull", "mspline"]) {
      expect(survivalStan(d).n_strata, `n_strata missing for ${d}`).toBe(1);
    }
  });

  it("the flexible baseline supplies the comparator bases", () => {
    const j = survivalStan("mspline");
    for (const k of ["pred_basis_cmp", "pred_ibasis_cmp", "rmst_ibasis_cmp"]) {
      expect(j, `missing ${k}`).toHaveProperty(k);
    }
    // One shared baseline, so the comparator grids are the index grids.
    expect(j.pred_basis_cmp).toEqual(j.pred_basis);
    expect(j.rmst_ibasis_cmp).toEqual(j.rmst_ibasis);
  });

  it("the random-walk prior fields are matrices, one column per stratum", () => {
    const j = survivalStan("mspline");
    const nScoef = j.n_scoef as number;
    const nStrata = j.n_strata as number;
    for (const k of ["lscoef_prior_mean", "lscoef_weights"]) {
      const m = j[k] as number[][];
      expect(Array.isArray(m), `${k} is not an array`).toBe(true);
      expect(Array.isArray(m[0]), `${k} is flat, Stan declares a matrix`).toBe(true);
      expect(m.length, `${k} rows`).toBe(nScoef - 1);
      expect(m[0].length, `${k} columns`).toBe(nStrata);
    }
  });

  it("the normal family weights its comparator rows", () => {
    const nex = exampleForFamily("normal");
    const base = buildMlumrData("normal", parseCsv(nex.ipdCsv), parseCsv(nex.agdCsv), nex.mapping);
    const data = addIntegration(base, nex.covariateSpecs as Record<string, CovariateSpec>, { nInt: 16 });
    const j = JSON.parse(stanDataJson(buildStanData(data, { model: "spfa" }))) as Record<string, unknown>;
    const w = j.agd_weight as number[];
    expect(Array.isArray(w), "agd_weight missing").toBe(true);
    expect(w.length).toBe(j.n_agd_rows);
    expect(w.every((x) => Number.isFinite(x) && x > 0)).toBe(true);
  });
});
