# knitr names an image file after its chunk, and these articles do not use
# unique chunk names: `forest`, `prior-post`, `predict-plot` and
# `posterior-areas` are each defined in several of them. While every article
# wrote into one shared `figure/` directory, the last one rendered owned the
# bytes at those paths, and a self-contained HTML built against that state
# embedded another article's plot.
#
# That is not hypothetical. Every image in the shipped continuous-outcomes.html
# belonged to a different article: a survival RMST forest in months, a count
# rate-ratio posterior, a psoriasis response prediction and a survival
# prior-posterior overlay. The tables and prose beside them were correct, which
# is why it survived review; a byte-integrity check would not have found it
# either, because the files were perfectly valid PNGs.
#
# The invariant that catches it is ownership: a plot generated by one article
# must not appear in another. This compares the actual embedded image bytes,
# so it holds regardless of what the file paths happen to be.

test_that("no shipped vignette embeds another vignette's figure", {
  vdir <- testthat::test_path("..", "..", "vignettes")
  skip_if_not(dir.exists(vdir),
              "run from a source checkout, not an installed package")
  html <- list.files(vdir, pattern = "[.]html$", full.names = TRUE)
  skip_if(length(html) < 2L, "needs at least two rendered articles")

  # One entry per (article, image digest).
  owners <- list()
  for (f in html) {
    txt <- paste(readLines(f, warn = FALSE), collapse = "\n")
    pattern <- "data:image/png;base64,[A-Za-z0-9+/=]+"
    b64 <- regmatches(txt, gregexpr(pattern, txt))[[1]]
    if (!length(b64)) next
    # The base64 payload IS the image, so comparing payloads compares images.
    # No decoding, and therefore no dependency, is needed to answer the only
    # question here: does this exact plot also appear somewhere else?
    payload <- sub("^data:image/png;base64,", "", b64)
    for (d in unique(payload)) {
      owners[[d]] <- c(owners[[d]], basename(f))
    }
  }
  skip_if(length(owners) == 0L, "no embedded images found")

  shared <- Filter(function(x) length(unique(x)) > 1L, owners)
  expect_length(shared, 0L)
  if (length(shared)) {
    # Name them, so a failure says which articles collided rather than only
    # that some did.
    msg <- paste(vapply(shared, function(x) {
      paste(sort(unique(x)), collapse = ", ")
    }, character(1)), collapse = "\n  ")
    fail(paste0("the same image is embedded in more than one article:\n  ", msg))
  }
})

test_that("the precompiler gives every article its own figure directory", {
  script <- testthat::test_path("..", "..", "vignettes", "precompile.R")
  skip_if_not(file.exists(script),
              "run from a source checkout, not an installed package")
  txt <- paste(readLines(script, warn = FALSE), collapse = "\n")
  # The mechanism, not the wording: the figure path must be derived from the
  # article being built rather than fixed.
  expect_true(grepl("fig.path", txt, fixed = TRUE))
  expect_true(grepl("stem", txt, fixed = TRUE))
})
