// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_binary_relaxed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_binary_spfa_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_normal_relaxed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_normal_spfa_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_poisson_relaxed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_poisson_spfa_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_survival_mspline_relaxed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_survival_mspline_spfa_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_survival_relaxed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mlumr_survival_spfa_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4mlumr_binary_relaxed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_binary_relaxed_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_binary_spfa_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_binary_spfa_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_normal_relaxed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_normal_relaxed_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_normal_spfa_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_normal_spfa_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_poisson_relaxed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_poisson_relaxed_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_poisson_spfa_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_poisson_spfa_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_survival_mspline_relaxed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_survival_mspline_relaxed_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_survival_mspline_spfa_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_survival_mspline_spfa_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_survival_relaxed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_survival_relaxed_mod, 0},
    {"_rcpp_module_boot_stan_fit4mlumr_survival_spfa_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mlumr_survival_spfa_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlumr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
